source "http://rubygems.org"
gem "shoulda"
gem "mocha"
gem "rake"
gem "ruby-debug"
gem "aws-s3", '0.6.4', :git=>"git://github.com/neshmi/aws-s3.git", :branch=>"master", :require=>"aws/s3"
gem "sqlite3-ruby", "~>1.3.0"
gem "appraisal"
